version: '3'

services:
  backend:
    build: .
    # ports:
    #   - 8000:8000
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=e_commerce
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_volume:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=ksrivatsan177@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
volumes:
  db_volume:
  pgadmin_volume:
    